requirements.txt
pip really struggles with xgboost, even when its already in the environment. This restores it as an optional dependency
=> remove shap and xgboost as hard deps

tobler/tests/test_interpolators.py, tobler/tests/test_pysal_integration.py
during pysal metapackage integration, we only need to test that the packages import, so this adds a simple test that does so.
this means we can skip the actual (long running) tests during pysal integration, as they are already run on the subpackages
=> add pysal integration/import test

.travis.yml, environment.yml, requirements.txt, tobler/data.py, tobler/tests/test_interpolators.py, tobler/util/util.py
this pr fixes some CRS handling for newer versions of geopandas/pyproj, pins to quilt 3.1.8 (currently later versions are broken), and makes some small changes to the way that path handling works for remote rasters. The new path handling doesnt actually work for our data in quilt (which was the whole point) because [rasterstats can't use an open rasterio handler](https://github.com/perrygeo/python-rasterstats/issues/208) but I'm leaving it in case that change is made upstream
=> quilt handling

.travis.yml, tobler/data.py, tobler/tests/test_download.py, tobler/tests/test_interpolators.py, tools/gitcount.ipynb
the default storage path works fine for most applications but fails on travis. This allows a user to specify a download location where the quilt package, which should make it easier to solve issues like these https://travis-ci.org/knaaptime/geosnap/jobs/653970124?utm_medium=notification&utm_source=email
=> allow specifying path for quilt storage

.ci/38.yml, tobler/tests/test_interpolators.py
It looks like quilt is not available for 3.8 on conda-forge:
So, I think that is why the ci couldn't solve for the testing env.
This PR starts some conditional skipping if quilt isn't available.
Looks to be [working](https://github.com/sjsrey/tobler/runs/863412852?check_suite_focus=true)
=> [TST] conditionally skip 3.8 tests needing quilt

.ci/37.yml, .ci/38.yml, .ci/39.yml, environment.yml, requirements.txt, requirements_tests.txt, tobler/area_weighted/area_interpolate.py, tobler/tests/test_interpolators.py
xref #104 
This is the latest version of single-core refactoring of `area_interpolate`. It turned out, that using pygeos-backed `STRtree` and its vectorized `query_bulk` in geopandas is even faster than the numba version @darribas mentioned in #104.
While pygeos is not strictly necessary and geopandas can use `rtree` for this operation, pygeos will bring speedup of the order of magnitude so I am adding it to requirements to make sure user have it installed.
=> REF: use STRtree.query_bulk in _area_tables_binning

.ci/37.yml, .ci/38.yml, .ci/39.yml, requirements_tests.txt, tobler/__init__.py, tobler/tests/test_utils.py, tobler/util/util.py
following the example of some similar code from the gdsbook, this adds a function to generate a geodataframe of h3 hexagons in the footprint of a given source gdf.  I think its useful to have around and i imagine would be useful to generate a target for interpolation
=> add hexify function

docs/api.rst, tobler/area_weighted/__init__.py, tobler/area_weighted/area_join.py, tobler/area_weighted/max_area.py, tobler/tests/test_area_join.py, tobler/tests/test_dasymetric.py
Closes #101
I am open to suggestions on the name and the placement of the function within tobler.
If there is no match for some rows in `target_df`, some column dtpyes (integer is not nullable) are not preserved and fall back to `object`.
Where to put an example? To the existing notebook or to a new one? And what is the relationship between those in `notebooks` and those in `docs/notebooks`, are they just duplicated?
=> ENH: add area_join for join based on the largest intersection

tobler/tests/test_utils.py, tobler/util/util.py
#125  is resolved by first exploding the input, then handling via split-apply-combine if the resulting unary_union is a multipolygon itself
=> hexify multipolygons

tobler/area_weighted/area_interpolate.py, tobler/tests/test_dasymetric.py
Hi,
we needed to transfer categorical data (land cover) so I used the existing `area_interpolate` and added support for categorical variables. It measures a ratio of each unique category present in each polygon. See the example below. 
```py
sac1 = load_example("Sacramento1")
sac2 = load_example("Sacramento2")
sac1 = geopandas.read_file(sac1.get_path("sacramentot2.shp"))
sac2 = geopandas.read_file(sac2.get_path("SacramentoMSA2.shp"))
categories = ["cat", "dog", "donkey", "wombat", "capybara"]
sac1["animal"] = (categories * ((len(sac1) // len(categories)) + 1))[
: len(sac1)
]
res = area_interpolate(
source_df=sac1,
target_df=sac2,
categorical_variables=["animal"],
)
```
```py
>>> print(res.head())
animal_cat  animal_dog  animal_donkey  animal_wombat  animal_capybara  \
0    0.431909 …
```
=> ENH: support categorical variables in area_interpolate

.ci/37.yml, .ci/38.yml, .ci/39.yml, docs/_static/references.bib, tobler/__init__.py, tobler/pycno/__init__.py, tobler/pycno/pycno.py, tobler/tests/test_pycno.py
resolves #95. Big thanks to @danlewis85
=> add pycnophylactic interpolation

.github/workflows/unittests.yml, tobler/tests/test_pycno.py
We should have scheduled tests running to catch potential issues with new versions sooner than we do any PR.
=> CI: schedule weekly tests

tobler/util/util.py
The latest geopandas is raising a warning in `explode` about the future change of the behaviour of an index. I wanted to add a keyword to silence it but then I realised that the `explode` is actually not needed here. We do the `unary_union` and the rest doesn't care about the multipolygons in the original input. So I removed it.
=> REF: remove explode from h3fy

tobler/area_weighted/area_interpolate.py, tobler/tests/test_area_interpolators.py
Closes #159
- switch to CSR
- test both CSR and DOK
- move `weights` creation behind relevant if statements so we don't compute them if they're not used
=> REF: switch to CSR matrix in area binning

.ci/37.yml, .ci/38.yml, .ci/39.yml, README.md, docs/notebooks/area_interpolate_perf.ipynb, environment.yml, requirements.txt, tobler/area_weighted/area_interpolate.py
Remove pygeos dependency and use geopandas GeometryArray logic instead. Compatible with both pygeos and shapely 2.
=> REF: move from pygeos to shapely 2

tobler/area_weighted/area_interpolate_dask.py
(also includes some minor blackening)
=> move dask to function-level import

tobler/pycno/pycno.py, tobler/tests/test_pycno.py
If your target gdf uses other than non-default index, resutls of pycno get misaligned because we create a Series with the rangeindex. The result can easily be all nan.
Assigning proper index. Will add test later.
=> BUG: fix misalignment of Series in pycno

tobler/tests/test_utils.py, tobler/util/util.py
=> BUG: fix support for 3D geometries in h3fy

README.md
Currently the CI badge on README links directly to the badge image. Updating that to link back to the action file page.
=> point testing badge testing page

tobler/dasymetric/raster_tools.py, tobler/tests/test_area_interpolators.py, tobler/util/util.py
GeoPandas now preserves the geometry column name if it has one. As a result, we end up with two columns called `hex_id` in the first step and a geometry assigned as an index in the second.
Fixed.
@knaaptime @jGaboardi we shall expand CI to test against nightly here. I caught it coincidentally when testing my teaching material against 1.0 alpha. 
Also, this will need a patch release fairly soon.
=> COMPAT: geopandas 1.0 compatibility fix in h3fy

.github/workflows/unittests.yml, ci/312-dev.yml
I think that the dev failures we're seeing in libpysal are actually coming from here. And we should test against dev versions anyway.
=> CI: include dev env in CI matrix

tobler/area_weighted/area_interpolate.py
This should fix the CI errors we are seeing. Probably worth cutting a patch release.
=> COMPAT: fix compatibility with scipy 1.15

.github/workflows/unittests.yml
Copied from libpysal and should resolve CI issue of [this](https://github.com/pysal/tobler/actions/runs/12820486430/job/35750122085) sort.
=> CI: fetch examples ahead of time

.github/workflows/unittests.yml
This PR:
* is a follow up of https://github.com/pysal/tobler/pull/223#issuecomment-2610842992
* trying to get recognition of true coverer report – 87% locally
=> try recognize coverage in CI

tobler/tests/test_utils.py
Should fix some failures but may break with older versions. Let's see.
The dev failure we see will need to be fixed in dask_geopandas.
=> update test to h3 4.2.0

ci/313-dev.yml
I merged the fix for our errors over in dask-geopandas but we need to actually use it here to get the CI green again.
=> CI: pull dask-geopandas dev in dev env
